src/WebUI/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using OverTheBoard.Infrastructure.Services;
using OverTheBoard.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using OverTheBoard.Data;
using OverTheBoard.Data.Entities;
using System.Security.Claims;
using System.Text;
using Microsoft.Extensions.Logging;
using OverTheBoard.Data.Entities.Applications;
using OverTheBoard.Infrastructure.Common;

namespace OverTheBoard.WebUI.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly IFileUploader _fileUploader;
        private readonly UserManager<OverTheBoardUser> _userManager;
        private readonly SignInManager<OverTheBoardUser> _signInManager;
        private readonly IUserService _userService;
        private readonly IGameService _gameService;
        private readonly ILogger<DashboardController> _logger;

        public DashboardController(IFileUploader fileUploader, 
            UserManager<OverTheBoardUser> userManager, 
            SignInManager<OverTheBoardUser> signInManager,
            IUserService userService,
            IGameService gameService,
            ILogger<DashboardController> logger
            )
        {
            _fileUploader = fileUploader;
            _userManager = userManager;
            _signInManager = signInManager;
            _userService = userService;
            _gameService = gameService;
            _logger = logger;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // Gets the users DisplayName and DisplayImage and returns the model to output it on the view
            var model = new DashboardViewModel();
            var user = await _userManager.GetUserAsync(User);
            model.DisplayName = user.DisplayName;
            model.DisplayImagePath = $"{user.DisplayImagePath}";
            model.Rating = user.Rating;

            var chartData = await _gameService.GetChartsDataAsync(user.Id);

            model.Charts = new ChessDataEngine(chartData).Build().ToString();
            return View(model);
        }
        

        [HttpGet]
        public async Task<IActionResult> Settings()
        {
            SettingsViewModel model = new SettingsViewModel();
            // Gets the users DisplayName and DisplayImage and returns the model to output it on the view
            var user = await _userManager.GetUserAsync(User);
            model.DisplayImagePath = user.DisplayImagePath;
            model.Email = user.Email;
            model.DisplayName = user.DisplayName;
            model.DisplayNameId = user.DisplayNameId;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Settings(SettingsViewModel model, IFormFile file)
        {
            var user = await _userManager.GetUserAsync(User);
            var filename = await _fileUploader.UploadImage(file, user.Id);
            //Checks if the display image pic has been uploaded to the site
            if (filename != null)
            {
                user.DisplayImagePath = $"Users\\{filename}";
                model.DisplayImagePath = $"Users\\{filename}";

            }

            else
            {
                model.DisplayImagePath = user.DisplayImagePath;
            }

            // TO-DO: Check if the username is in database
            //Checks and then changes the DisplayName
            if (model.DisplayName != null &&  !await UserClash(model.DisplayName, user.DisplayNameId))
            {
                user.DisplayName = model.DisplayName;
            }
            else
            {
                ModelState.AddModelError("DisplayName", "Username clashes with an existing user please enter another username" );
            }
            if (model.OldPassword != null && model.NewPassword != null)
            {
                var result = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                if (result.Succeeded)
                {
                    if (user != null)
                    {
                        await _signInManager.SignInAsync(user, isPersistent: false);
                        return View(model);
                    }
                }
            }

            // Sets the Email an DisplayName of the model to be output in the SettingsView
            model.Email = user.Email;
            model.DisplayName = user.DisplayName;
            model.DisplayNameId = user.DisplayNameId;
            await _userManager.UpdateAsync(user);
            return View(model);
            
        }
        public async Task<IActionResult> GameHistory()
        {
            var model = new GameHistoryViewModel();
            var userId = GetUserId();
            var games = await _gameService.GetGameByUserIdAsync(userId, GameStatus.Completed);
            model.gamesCompleted = games;
            return View(model);
        }
        public async Task<IActionResult> Leaderboard()
        {
            var model = new LeaderboardViewModel();
            
            model.YourDetails = await GetYourDetailsAsync();
            model.TopRanks = await GetTopRanksAsync();
            return View(model);
        }

        private async Task<List<GamePlayerStatsModel>> GetTopRanksAsync()
        {
            var statsModels = new List<GamePlayerStatsModel>();
            var users = await _userService.GetTopRatingUsersAsync(10);
            foreach (var user in users)
            {
                var stats = await _gameService.GetStatsByUserAsync(user.Id);
                statsModels.Add(new GamePlayerStatsModel() { DisplayName =user.DisplayName, Matches = stats.TotalGame, Win = stats.TotalWin, Lose = stats.TotalLose, Draw = stats.TotalDraw, Point = user.Rating });
            }

            return statsModels;
        }

        private async Task<List<KeyValuePair<string,string>>> GetYourDetailsAsync()
        {
            
            var user = await _userManager.GetUserAsync(User);
            var stats = await _gameService.GetStatsByUserAsync(user.Id);
            var keyValuePairs = new List<KeyValuePair<string, string>>();
            keyValuePairs.Add(new KeyValuePair<string, string>("Rating", user.Rating.ToString()));
            keyValuePairs.Add(new KeyValuePair<string, string>("Rank", user.Rank.ToString()));
            keyValuePairs.Add(new KeyValuePair<string, string>("Total Games", stats.TotalGame.ToString()));
            keyValuePairs.Add(new KeyValuePair<string, string>("Total Win", stats.TotalWin.ToString()));
            keyValuePairs.Add(new KeyValuePair<string, string>("Total Lose", stats.TotalLose.ToString()));
            keyValuePairs.Add(new KeyValuePair<string, string>("Total Draw", stats.TotalDraw.ToString()));
            return keyValuePairs;
        }

        public IActionResult Analysis()
        {
            return View();
        }


        private async Task<bool> UserClash(string displayName, string displayNameId)
        {
            var user = await _userService.GetUserDisplayNameAndyNameIdAsync(displayName, displayNameId);
            if (user != null)
            {
                return true;
            }
            return false;
        }

        private string GetUserId()
        {
            return User
                .FindFirst(ClaimTypes.NameIdentifier)?.Value;
        }
    }
}

src/WebUI/Controllers/PlayController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.SignalR;
using OverTheBoard.ObjectModel;
using OverTheBoard.WebUI.SignalR;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.EntityFrameworkCore;
using OverTheBoard.Data;
using OverTheBoard.Data.Entities;
using OverTheBoard.Infrastructure.Services;
using OverTheBoard.WebUI.Models;
using OverTheBoard.Data.Entities.Applications;
using OverTheBoard.WebUI.ModelPopulators;

namespace OverTheBoard.WebUI.Controllers
{
    [Authorize]
    [Route("play")]
    public class PlayController : Controller
    {
        private readonly IGameService _gameService;
        private readonly ITournamentService _tournamentService;
        private readonly IUserService _userService;
        private readonly IEloService _eloService;
        private readonly IBracketsViewModelPopulator _bracketsViewModelPopulator;

        public PlayController(IGameService gameService, ITournamentService tournamentService,
            IUserService userService, IEloService eloService, IBracketsViewModelPopulator bracketsViewModelPopulator)
        {
            _gameService = gameService;
            _tournamentService = tournamentService;
            _userService = userService;
            _eloService = eloService;
            _bracketsViewModelPopulator = bracketsViewModelPopulator;
        }
        public async Task<IActionResult> Index()
        {
            var model = new PlayViewModel();
            var userId = GetUserId();
            var games = await _gameService.GetGameByUserIdAsync(userId, GameStatus.InProgress);
            model.gameInProgress = games;
            return View(model);
        }

        [HttpGet("unranked")]
        public IActionResult Unranked()
        {
            return View();
        }

        [HttpGet("brackets")]
        public async Task<IActionResult> Brackets()
        {
            var userId = GetUserId();
            var activeTournamentIdentifier = await _tournamentService.GetTournamentIdentifierByUserAsync(userId);
            if (string.IsNullOrEmpty(activeTournamentIdentifier))
            {
                return View(new BracketsViewModel(){Items = new Dictionary<int, BracketsRoundItemModel>(), StatModels = new List<GamePlayerStatsModel>()});
            }
            var tournament = await _tournamentService.GetTournamentAsync(activeTournamentIdentifier);
            var games = await _gameService.GetMatchesByTournamentAsync(activeTournamentIdentifier);

            Dictionary<string, OverTheBoardUser> users = new Dictionary<string, OverTheBoardUser>(StringComparer.InvariantCultureIgnoreCase);
            foreach (var player in tournament.Players)
            {
                var user = await _userService.GetUserAsync(player.UserId);
                users.Add(player.UserId, user);
            }

            BracketsViewModel model = _bracketsViewModelPopulator.Populate(userId, tournament, games, users);
            return View(model);
        }

        
        [HttpGet("game/start-unranked")]
        public IActionResult StartUnranked(string sessionId)
        {
            return RedirectToAction("Game", new { sessionId = Guid.NewGuid().ToString(), type = GameType.Unranked.ToString().ToLower()});
        }

        //TODO Rename sessionId to gameId
        [HttpGet("game/{gameId}")]
        public async Task<IActionResult> Game(string gameId)
        {
            
            var model = new GameViewModel();
            var userId = GetUserId();
            var game =  await _gameService.GetChessGameWithPlayersAsync(gameId);
            var currentPlayer = game.Players.FirstOrDefault(e => e.UserId.Equals(userId));
            if (currentPlayer == null)
            {
                throw new Exception("User does not exists");
            }
            var opponentPlayer = game.Players.FirstOrDefault(e => !e.UserId.Equals(userId));

            if (opponentPlayer != null && currentPlayer != null)
            {
                var opponentUser = await _userService.GetUserAsync(opponentPlayer.UserId);
                var currentUser = await _userService.GetUserAsync(userId);

                model.CurrentDisplayName = currentUser.DisplayName;
                model.OpponentDisplayName = opponentUser.DisplayName;

                model.CurrentColour = currentPlayer.Colour;
                model.OpponentColour = opponentPlayer.Colour;

                model.CurrentRating = currentUser.Rating;
                model.OpponentRating = opponentUser.Rating;

                var currentEloOutcomes = await _eloService.CalculateEloRatingChangeAsync(currentUser.Rating, opponentUser.Rating);

                foreach (var outcome in currentEloOutcomes)
                {
                    switch (outcome.Type)
                    {
                        case EloOutcomesType.Win:
                            model.CurrentEloChangeOnWin = outcome.Value;
                            break;
                        case EloOutcomesType.Lose:
                            model.CurrentEloChangeOnLose = outcome.Value;
                            break;
                        case EloOutcomesType.Draw:
                            model.CurrentEloChangeOnDraw = outcome.Value;
                            break;
                    }
                }
            }

            return View(model);
        }
        
        
        private string GetUserId()
        {
            return User
                .FindFirst(ClaimTypes.NameIdentifier)?.Value;
        }
    }

    
}

src/WebUI/Views/Shared/_Layout.cshtml
@{
    Layout = "_LayoutMaster";
}

<div>
    <div class="gtco-loader"></div>
    <div id="page">
        <nav class="gtco-nav" role="navigation">
            <div class="gtco-container">

                <div class="row">
                    <div class="col-sm-2 col-xs-12">
                        <div><a asp-controller="Dashboard" asp-action="Index"><img src="/images/logo.png" alt="OverTheBoard Logo"></a><a class="text-white-important" asp-controller="Dashboard" asp-action="Index">&nbsp;&nbsp;<strong>OverTheBoard</strong></a></div>
                    </div>
                    <div class="col-lg-10 text-xl-left menu-1">
                        <ul>
                            <li><a asp-controller="Dashboard" asp-action="Index">Home</a></li>
                            <li><a asp-controller="Play" asp-action="Index">Play</a></li>
                            <li><a asp-controller="Dashboard" asp-action="Leaderboard">Leaderboard</a></li>
                            <li><a asp-controller="Dashboard" asp-action="GameHistory">Analysis</a></li>
                            <li><a asp-controller="Dashboard" asp-action="Settings">Settings</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        @RenderBody()
        <footer id="gtco-footer-no-padding" class="gtco-section" role="contentinfo">
            <div class="gtco-copyright">
                <div class="gtco-container">
                    <div class="row">
                        <div class="col-md-6 text-left">
                            <p><small>&copy; Annoor Mustafi </small></p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>


@section scripts {
    @RenderSection("scripts", false)
}

@section styles{
    @RenderSection("styles", false)
}

src/WebUI/Views/Shared/_LayoutAccount.cshtml
@{
    Layout = "_LayoutMaster";
}

<div>
    <div class="gtco-loader"></div>
    <div id="page" class="gtco-background">
        <nav class="gtco-nav device-only" role="navigation">
            <div class="gtco-container">
                <div class="row">
                    <div class="col-xs-10 text-right menu-1">
                        <ul>
                            <li><a href="/">Home</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <div class="gtco-container">
            <div class="row">
                <div class="col-md-12 col-md-offset-0 text-left">
                    <div class="display-t reg-top-padding">
                        <div class="display-tc">
                            <div class="row reg-top-padding">
                                <div class="text-center"><a asp-controller="Home" asp-action="Index"><img src="/images/logo.png" alt="OverTheBoard Logo"></a></div>
                            </div>
                            <div class="row">
                                <div class="col-md-4 text-center header-img animate-box"></div>
                                <div class="col-md-4 rounded">
                                    @RenderBody()
                                </div>
                                <div class="col-md-4 text-center header-img animate-box"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts {
    @RenderSection("scripts", false)
}

@section styles{
    @RenderSection("styles", false)
}

src/WebUI/Views/Shared/_LayoutHome.cshtml
@{
    Layout = "_LayoutMaster";
}

<div>
    <div class="gtco-loader"></div>
    <div id="page">

        <nav class="gtco-nav" role="navigation">
            <div class="gtco-container">

                <div class="row">
                    <div class="col-sm-2 col-xs-12">
                        <div><a asp-controller="Home" asp-action="Index"><img src="/images/logo.png" alt="OverTheBoard Logo"></a><a class="text-white-important" asp-controller="Home" asp-action="Index">&nbsp;&nbsp;<strong>OverTheBoard</strong></a></div>
                    </div>
                </div>

            </div>
        </nav>
        @RenderBody()
        <footer id="gtco-footer" class="gtco-section" role="contentinfo">
            <div class="gtco-container">
                <div class="row row-pb-md">
                    <div class="col-md-8 col-md-offset-2 gtco-cta text-center">
                        <h3>OverTheBoard</h3>
                        <p>Chess is regarded as a highly competitive game for people to get into, hence why OTB was created to give players a sense of the competitive nature of the game. To make the jump from standard chess to OTB easier, tournament systems have been added in. Also, leagues gives players a clear understanding of one’s skills and the tournament systems allows for more competitive gameplay, since players have to beat others to get to the top! Make sure to have fun and of course, destroy everyone in chess!</p>
                    </div>
                </div>

            </div>
            <div class="gtco-copyright">
                <div class="gtco-container">
                    <div class="row">
                        <div class="col-md-6 text-left">
                            <p><small>&copy; Annoor Mustafi </small></p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>

    </div>
</div>


@section scripts {
    @RenderSection("scripts", false)
}

@section styles{
    @RenderSection("styles", false)
}

src/WebUI/Views/Shared/_LayoutMaster.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>OverTheBoard</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Play Chess" />
    <meta name="keywords" content="Chess" />
    <meta name="author" content="Beed" />

    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,700" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="~/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/css/icomoon.css">
    <!-- Themify Icons-->
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/css/bootstrap.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- Modernizr JS -->
    <script src="~/js/modernizr-2.6.2.min.js"></script>
    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="~/js/respond.min.js"></script>
    <![endif]-->
    @RenderSection("styles", false)

</head>
<body>
    @RenderBody()
        
    <!-- jQuery -->
    <script src="~/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/js/jquery.waypoints.min.js"></script>
    <!-- Carousel -->
    <script src="~/js/owl.carousel.min.js"></script>
    <!-- Magnific Popup -->
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/magnific-popup-options.js"></script>
    <!-- Main -->
    <script src="~/js/main.js"></script>

    @RenderSection("scripts", false)

</body>
</html>